export const SERVICES = {
  MEMBERS: 'MEMBERS_SERVICE',
  PRODUCTS: 'PRODUCTS_SERVICE',
  TEAMS: 'TEAMS_SERVICE',
  SHIPMENTS: 'SHIPMENTS_SERVICE',
  HISTORY: 'HISTORY_SERVICE',
  TENANTS: 'TENANTS_SERVICE',
} as const;
